name: Deploy Backend to Railway

on:
  push:
    branches:
      - main  # Adjust branch name if needed
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v18
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --omit=dev

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service backend

      - name: Run Backend Health Check
        run: npm run monitor
